# Generated by Django 5.1.1 on 2024-10-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('apodo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=128)),
                ('foto_de_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
        ),
    ]
